// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import CustomerServiceOutlined from '/Users/colorpool/Downloads/AI_Onsite/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/CustomerServiceOutlined';
import TeamOutlined from '/Users/colorpool/Downloads/AI_Onsite/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/TeamOutlined';
import FileTextOutlined from '/Users/colorpool/Downloads/AI_Onsite/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/FileTextOutlined';
import IdcardOutlined from '/Users/colorpool/Downloads/AI_Onsite/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/IdcardOutlined';
import ShoppingCartOutlined from '/Users/colorpool/Downloads/AI_Onsite/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/ShoppingCartOutlined';
import DashboardOutlined from '/Users/colorpool/Downloads/AI_Onsite/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/DashboardOutlined';
import BellOutlined from '/Users/colorpool/Downloads/AI_Onsite/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/BellOutlined';
import GroupOutlined from '/Users/colorpool/Downloads/AI_Onsite/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/GroupOutlined';
import TrophyOutlined from '/Users/colorpool/Downloads/AI_Onsite/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/TrophyOutlined';
import UserOutlined from '/Users/colorpool/Downloads/AI_Onsite/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/UserOutlined';
import ProfileOutlined from '/Users/colorpool/Downloads/AI_Onsite/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/ProfileOutlined';
import UserAddOutlined from '/Users/colorpool/Downloads/AI_Onsite/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/UserAddOutlined';
import ExperimentOutlined from '/Users/colorpool/Downloads/AI_Onsite/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/ExperimentOutlined';
import LineChartOutlined from '/Users/colorpool/Downloads/AI_Onsite/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/LineChartOutlined';
import MessageOutlined from '/Users/colorpool/Downloads/AI_Onsite/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/MessageOutlined';
import CommentOutlined from '/Users/colorpool/Downloads/AI_Onsite/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/CommentOutlined';
import ArrowUpOutlined from '/Users/colorpool/Downloads/AI_Onsite/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/ArrowUpOutlined';
import BookOutlined from '/Users/colorpool/Downloads/AI_Onsite/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/BookOutlined';
import ShareAltOutlined from '/Users/colorpool/Downloads/AI_Onsite/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/ShareAltOutlined';
import SettingOutlined from '/Users/colorpool/Downloads/AI_Onsite/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/SettingOutlined';
import BarChartOutlined from '/Users/colorpool/Downloads/AI_Onsite/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/BarChartOutlined';
import DatabaseOutlined from '/Users/colorpool/Downloads/AI_Onsite/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/DatabaseOutlined';
import RobotOutlined from '/Users/colorpool/Downloads/AI_Onsite/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/RobotOutlined';
import UserSwitchOutlined from '/Users/colorpool/Downloads/AI_Onsite/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/UserSwitchOutlined';
import EyeOutlined from '/Users/colorpool/Downloads/AI_Onsite/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/EyeOutlined';
import CarOutlined from '/Users/colorpool/Downloads/AI_Onsite/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/CarOutlined';
import TagsOutlined from '/Users/colorpool/Downloads/AI_Onsite/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/TagsOutlined';
import BulbOutlined from '/Users/colorpool/Downloads/AI_Onsite/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/BulbOutlined';
import RiseOutlined from '/Users/colorpool/Downloads/AI_Onsite/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/RiseOutlined';
import CrownOutlined from '/Users/colorpool/Downloads/AI_Onsite/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/CrownOutlined';
import BankOutlined from '/Users/colorpool/Downloads/AI_Onsite/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/BankOutlined';
import KeyOutlined from '/Users/colorpool/Downloads/AI_Onsite/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/KeyOutlined';
export default { CustomerServiceOutlined, TeamOutlined, FileTextOutlined, IdcardOutlined, ShoppingCartOutlined, DashboardOutlined, BellOutlined, GroupOutlined, TrophyOutlined, UserOutlined, ProfileOutlined, UserAddOutlined, ExperimentOutlined, LineChartOutlined, MessageOutlined, CommentOutlined, ArrowUpOutlined, BookOutlined, ShareAltOutlined, SettingOutlined, BarChartOutlined, DatabaseOutlined, RobotOutlined, UserSwitchOutlined, EyeOutlined, CarOutlined, TagsOutlined, BulbOutlined, RiseOutlined, CrownOutlined, BankOutlined, KeyOutlined };
