// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import DashboardOutlined from '/Users/colorpool/Downloads/AI_Onsite/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/DashboardOutlined';
import BellOutlined from '/Users/colorpool/Downloads/AI_Onsite/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/BellOutlined';
import GroupOutlined from '/Users/colorpool/Downloads/AI_Onsite/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/GroupOutlined';
import TrophyOutlined from '/Users/colorpool/Downloads/AI_Onsite/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/TrophyOutlined';
import TeamOutlined from '/Users/colorpool/Downloads/AI_Onsite/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/TeamOutlined';
import UserOutlined from '/Users/colorpool/Downloads/AI_Onsite/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/UserOutlined';
import UserAddOutlined from '/Users/colorpool/Downloads/AI_Onsite/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/UserAddOutlined';
import CustomerServiceOutlined from '/Users/colorpool/Downloads/AI_Onsite/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/CustomerServiceOutlined';
import FileTextOutlined from '/Users/colorpool/Downloads/AI_Onsite/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/FileTextOutlined';
import ExperimentOutlined from '/Users/colorpool/Downloads/AI_Onsite/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/ExperimentOutlined';
import LineChartOutlined from '/Users/colorpool/Downloads/AI_Onsite/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/LineChartOutlined';
import MessageOutlined from '/Users/colorpool/Downloads/AI_Onsite/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/MessageOutlined';
import CommentOutlined from '/Users/colorpool/Downloads/AI_Onsite/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/CommentOutlined';
import ArrowUpOutlined from '/Users/colorpool/Downloads/AI_Onsite/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/ArrowUpOutlined';
import BookOutlined from '/Users/colorpool/Downloads/AI_Onsite/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/BookOutlined';
import ShoppingCartOutlined from '/Users/colorpool/Downloads/AI_Onsite/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/ShoppingCartOutlined';
import ShareAltOutlined from '/Users/colorpool/Downloads/AI_Onsite/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/ShareAltOutlined';
import SettingOutlined from '/Users/colorpool/Downloads/AI_Onsite/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/SettingOutlined';
import BarChartOutlined from '/Users/colorpool/Downloads/AI_Onsite/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/BarChartOutlined';
import DatabaseOutlined from '/Users/colorpool/Downloads/AI_Onsite/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/DatabaseOutlined';
import RobotOutlined from '/Users/colorpool/Downloads/AI_Onsite/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/RobotOutlined';
import UserSwitchOutlined from '/Users/colorpool/Downloads/AI_Onsite/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/UserSwitchOutlined';
import EyeOutlined from '/Users/colorpool/Downloads/AI_Onsite/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/EyeOutlined';
import CarOutlined from '/Users/colorpool/Downloads/AI_Onsite/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/CarOutlined';
import TagsOutlined from '/Users/colorpool/Downloads/AI_Onsite/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/TagsOutlined';
export default { DashboardOutlined, BellOutlined, GroupOutlined, TrophyOutlined, TeamOutlined, UserOutlined, UserAddOutlined, CustomerServiceOutlined, FileTextOutlined, ExperimentOutlined, LineChartOutlined, MessageOutlined, CommentOutlined, ArrowUpOutlined, BookOutlined, ShoppingCartOutlined, ShareAltOutlined, SettingOutlined, BarChartOutlined, DatabaseOutlined, RobotOutlined, UserSwitchOutlined, EyeOutlined, CarOutlined, TagsOutlined };
